server:
  port: 8084
spring:
  application:
    name: pragma-config
  cloud:
    config:
      server:
        git:
          username: SerBuitrago
          password: 3118938189Se3114794520
          uri: https://github.com/SerBuitrago/microservice-client.git
          search-paths: pragma-config-data     
          default-label: main