version: '3.7'
services:
  pragma-config:
    images: pragma-config:v1
    ports:
      - "8084:8084"
    restart: always
    networks:
      - microservice-client
  pragma-eureka:
    images: pragma-eureka:v1
    ports:
      - "8761:8761"
    restart: always
    networks:
      - microservice-client
networks:
  microservice-client: