server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    zipkin: 
        base-url: http://localhost:9411
        sender: 
            type: rabbit
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
       default-zone: http://pragma-eureka:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}