server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://pragma-mysql:3306/${spring.application.name}
    username: root
    password: root
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
       default-zone: http://pragma-eureka:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}